java_library(
    name = 'java',
    srcs = glob(['**/*.java']),
    deps = [],
    resources = [
        '//third-party:LICENSE-Apache-2.0',
    ],
    resource_strip_prefix = 'third-party/',
    visibility = ['//visibility:public'],
)
