java_test(
    name = "test",
    srcs = glob(['**/*Test.java']),
    deps = [
        '//java:java',
        '//third-party:junit',
        '//third-party:hamcrest-library',
    ],
    size = 'small',
)
